wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1668096129.389161
    t:
      1:
      - 5
      - 6
      - 8
      - 53
      - 55
      2:
      - 5
      - 6
      - 8
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.7.9
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
bootstrap:
  desc: null
  value: true
criterion:
  desc: null
  value: squared_error
max_samples:
  desc: null
  value: 0.5
n_estimators:
  desc: null
  value: 200
random_state:
  desc: null
  value: 42
